# -*- mode: python ; coding: utf-8 -*-

import PyInstaller.utils.hooks as hooks

block_cipher = None

# Collect win10toast data files
try:
    win10toast_datas = hooks.collect_data_files('win10toast')
    # Ensure it's a list
    if not isinstance(win10toast_datas, list):
        win10toast_datas = list(win10toast_datas) if win10toast_datas else []
except Exception:
    win10toast_datas = []

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('assets', 'assets'), ('config.json', '.')] + win10toast_datas,
    hiddenimports=[
        'win10toast',
        'pynput.keyboard',
        'pynput.mouse',
        'pyautogui',
        'pygetwindow',
        'tkinter',
        'win10toast.toast',
        'pydirectinput',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy.distutils',
        'scipy',
        'PIL',
        'pandas',
        'IPython',
        'jupyter',
        'notebook',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'test',
        'unittest',
        'email',
        'http',
        'xml',
        'pydoc',
        'doctest',
        'multiprocessing',
        'concurrent.futures',
        'asyncio',
        'dbm',
        'sqlite3',
        'xmlrpc',
        'distutils',
        'setuptools',
        'lib2to3',
        'wsgiref',
        'html',
        'tkinter.test',
        'tkinter.dnd2',
        'tkinter.scrolledtext',
        'tkinter.colorchooser',
        'tkinter.commondialog',
        'tkinter.dnd',
        'tkinter.font',
        'tkinter.tix',
        'tkinter.ttk',
        # Exclude heavy OpenCV modules we don't need
        'cv2.videoio',
        'cv2.gapi',
        'cv2.ml',
        'cv2.objdetect',
        'cv2.photo',
        'cv2.video',
        'cv2.dnn',
        'cv2.features2d',
        'cv2.calib3d',
        'cv2.ximgproc',
        'cv2.text',
        'cv2.aruco',
        'cv2.bgsegm',
        'cv2.bioinspired',
        'cv2.ccalib',
        'cv2.datasets',
        'cv2.dnn_superres',
        'cv2.face',
        'cv2.freetype',
        'cv2.fuzzy',
        'cv2.hdf',
        'cv2.hfs',
        'cv2.img_hash',
        'cv2.intensity_transform',
        'cv2.line_descriptor',
        'cv2.mcc',
        'cv2.optflow',
        'cv2.phase_unwrapping',
        'cv2.plot',
        'cv2.quality',
        'cv2.rapid',
        'cv2.reg',
        'cv2.rgbd',
        'cv2.saliency',
        'cv2.sfm',
        'cv2.shape',
        'cv2.stereo',
        'cv2.structured_light',
        'cv2.superres',
        'cv2.surface_matching',
        'cv2.tracking',
        'cv2.wechat_qrcode',
        'cv2.xfeatures2d',
        'cv2.xobjdetect',
        'cv2.xphoto',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DNA-Bot-Expulsion',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,  # Enable UPX compression if available
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='NONE',
)

